### ISSUE TITLE
NavigationBar ButtonItem, ButtonItems, UITableViewController 子类问题

### ISSUE THREAD

**Issue by liuyong** [youxingge/TMNavigationController#2]
self.navigationItem.leftBarButtonItem,
self.navigationItem.leftBarButtonItems,
self.navigationItem.rightBarButtonItem,
self.navigationItem.rightBarButtonItems
无效
和 UITableViewController的子类时，位置错乱，
盼解决，谢谢。

**Comment by youxingge** [comment]
系统的navigationItem已经hidden了
